export const foodNutritionData = [
  {
    id: 1,
    name: 'Frozen Yogurt',
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    calcium: '14%',
    iron: '1%',
  },
  {
    id: 2,
    name: 'Ice cream sandwich',
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    calcium: '8%',
    iron: '1%',
  },
  {
    id: 3,
    name: 'Eclair',
    calories: 262,
    fat: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    calcium: '6%',
    iron: '7%',
  },
  {
    id: 4,
    name: 'Cupcake',
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    calcium: '3%',
    iron: '8%',
  },
  {
    id: 5,
    name: 'Gingerbread',
    calories: 356,
    fat: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    calcium: '7%',
    iron: '16%',
  },
  {
    id: 6,
    name: 'Jelly bean',
    calories: 375,
    fat: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 7,
    name: 'Lollipop',
    calories: 392,
    fat: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    calcium: '0%',
    iron: '2%',
  },
  {
    id: 8,
    name: 'Honeycomb',
    calories: 408,
    fat: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    calcium: '0%',
    iron: '45%',
  },
  {
    id: 9,
    name: 'Donut',
    calories: 452,
    fat: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    calcium: '2%',
    iron: '22%',
  },
  {
    id: 10,
    name: 'KitKat',
    calories: 518,
    fat: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    calcium: '12%',
    iron: '6%',
  },
  {
    id: 11,
    name: 'Chocolate Chip Cookie',
    calories: 488,
    fat: 23.0,
    carbs: 64,
    protein: 5.8,
    sodium: 365,
    calcium: '5%',
    iron: '12%',
  },
  {
    id: 12,
    name: 'Vanilla Ice Cream',
    calories: 207,
    fat: 11.0,
    carbs: 24,
    protein: 3.5,
    sodium: 80,
    calcium: '11%',
    iron: '1%',
  },
  {
    id: 13,
    name: 'Strawberry Shortcake',
    calories: 344,
    fat: 15.2,
    carbs: 49,
    protein: 4.8,
    sodium: 289,
    calcium: '8%',
    iron: '9%',
  },
  {
    id: 14,
    name: 'Apple Pie',
    calories: 411,
    fat: 19.4,
    carbs: 57,
    protein: 3.7,
    sodium: 327,
    calcium: '4%',
    iron: '6%',
  },
  {
    id: 15,
    name: 'Cheesecake',
    calories: 321,
    fat: 22.5,
    carbs: 25,
    protein: 5.5,
    sodium: 438,
    calcium: '9%',
    iron: '3%',
  },
  {
    id: 16,
    name: 'Brownies',
    calories: 466,
    fat: 20.3,
    carbs: 68,
    protein: 6.8,
    sodium: 175,
    calcium: '4%',
    iron: '15%',
  },
  {
    id: 17,
    name: 'Tiramisu',
    calories: 240,
    fat: 15.8,
    carbs: 21,
    protein: 4.6,
    sodium: 134,
    calcium: '7%',
    iron: '4%',
  },
  {
    id: 18,
    name: 'Macarons',
    calories: 95,
    fat: 3.2,
    carbs: 15,
    protein: 2.1,
    sodium: 15,
    calcium: '1%',
    iron: '1%',
  },
  {
    id: 19,
    name: 'Churros',
    calories: 312,
    fat: 17.8,
    carbs: 35,
    protein: 4.2,
    sodium: 201,
    calcium: '3%',
    iron: '8%',
  },
  {
    id: 20,
    name: 'Creme Brulee',
    calories: 286,
    fat: 23.7,
    carbs: 16,
    protein: 4.2,
    sodium: 67,
    calcium: '12%',
    iron: '2%',
  },
  {
    id: 21,
    name: 'Pancakes',
    calories: 227,
    fat: 9.2,
    carbs: 28,
    protein: 6.2,
    sodium: 439,
    calcium: '11%',
    iron: '7%',
  },
  {
    id: 22,
    name: 'Waffles',
    calories: 291,
    fat: 14.7,
    carbs: 33,
    protein: 7.9,
    sodium: 383,
    calcium: '19%',
    iron: '11%',
  },
  {
    id: 23,
    name: 'Muffin',
    calories: 377,
    fat: 18.6,
    carbs: 48,
    protein: 6.8,
    sodium: 297,
    calcium: '6%',
    iron: '9%',
  },
  {
    id: 24,
    name: 'Croissant',
    calories: 406,
    fat: 21.0,
    carbs: 45,
    protein: 8.2,
    sodium: 424,
    calcium: '2%',
    iron: '12%',
  },
  {
    id: 25,
    name: 'Danish Pastry',
    calories: 374,
    fat: 20.3,
    carbs: 45,
    protein: 6.6,
    sodium: 320,
    calcium: '4%',
    iron: '8%',
  },
  {
    id: 26,
    name: 'Cinnamon Roll',
    calories: 420,
    fat: 16.8,
    carbs: 65,
    protein: 7.3,
    sodium: 430,
    calcium: '5%',
    iron: '10%',
  },
  {
    id: 27,
    name: 'Bagel',
    calories: 289,
    fat: 1.4,
    carbs: 56,
    protein: 11.3,
    sodium: 561,
    calcium: '6%',
    iron: '15%',
  },
  {
    id: 28,
    name: 'French Toast',
    calories: 149,
    fat: 7.0,
    carbs: 16,
    protein: 5.0,
    sodium: 311,
    calcium: '6%',
    iron: '5%',
  },
  {
    id: 29,
    name: 'Scone',
    calories: 362,
    fat: 14.5,
    carbs: 52,
    protein: 7.8,
    sodium: 622,
    calcium: '9%',
    iron: '11%',
  },
  {
    id: 30,
    name: 'Banana Bread',
    calories: 326,
    fat: 10.5,
    carbs: 54,
    protein: 4.9,
    sodium: 181,
    calcium: '3%',
    iron: '6%',
  },
  {
    id: 31,
    name: 'Chocolate Cake',
    calories: 352,
    fat: 14.3,
    carbs: 56,
    protein: 5.0,
    sodium: 299,
    calcium: '4%',
    iron: '18%',
  },
  {
    id: 32,
    name: 'Red Velvet Cake',
    calories: 333,
    fat: 13.2,
    carbs: 53,
    protein: 4.1,
    sodium: 318,
    calcium: '6%',
    iron: '8%',
  },
  {
    id: 33,
    name: 'Carrot Cake',
    calories: 408,
    fat: 21.0,
    carbs: 56,
    protein: 4.0,
    sodium: 348,
    calcium: '4%',
    iron: '7%',
  },
  {
    id: 34,
    name: 'Pound Cake',
    calories: 367,
    fat: 16.4,
    carbs: 53,
    protein: 4.4,
    sodium: 298,
    calcium: '3%',
    iron: '5%',
  },
  {
    id: 35,
    name: 'Angel Food Cake',
    calories: 72,
    fat: 0.2,
    carbs: 16,
    protein: 1.6,
    sodium: 212,
    calcium: '1%',
    iron: '1%',
  },
  {
    id: 36,
    name: 'Lemon Bars',
    calories: 318,
    fat: 12.8,
    carbs: 49,
    protein: 4.2,
    sodium: 178,
    calcium: '3%',
    iron: '6%',
  },
  {
    id: 37,
    name: 'Pecan Pie',
    calories: 503,
    fat: 27.0,
    carbs: 64,
    protein: 6.0,
    sodium: 320,
    calcium: '3%',
    iron: '8%',
  },
  {
    id: 38,
    name: 'Key Lime Pie',
    calories: 356,
    fat: 18.7,
    carbs: 45,
    protein: 4.5,
    sodium: 165,
    calcium: '8%',
    iron: '3%',
  },
  {
    id: 39,
    name: 'Pumpkin Pie',
    calories: 316,
    fat: 14.4,
    carbs: 41,
    protein: 7.0,
    sodium: 349,
    calcium: '10%',
    iron: '7%',
  },
  {
    id: 40,
    name: 'Fruit Tart',
    calories: 256,
    fat: 11.3,
    carbs: 38,
    protein: 3.8,
    sodium: 124,
    calcium: '4%',
    iron: '5%',
  },
  {
    id: 41,
    name: 'Chocolate Mousse',
    calories: 447,
    fat: 33.0,
    carbs: 33,
    protein: 6.1,
    sodium: 87,
    calcium: '8%',
    iron: '11%',
  },
  {
    id: 42,
    name: 'Bread Pudding',
    calories: 219,
    fat: 7.8,
    carbs: 31,
    protein: 6.5,
    sodium: 292,
    calcium: '12%',
    iron: '6%',
  },
  {
    id: 43,
    name: 'Rice Pudding',
    calories: 142,
    fat: 2.5,
    carbs: 27,
    protein: 4.0,
    sodium: 95,
    calcium: '9%',
    iron: '2%',
  },
  {
    id: 44,
    name: 'Flan',
    calories: 223,
    fat: 6.6,
    carbs: 35,
    protein: 7.2,
    sodium: 101,
    calcium: '15%',
    iron: '3%',
  },
  {
    id: 45,
    name: 'Gelato',
    calories: 160,
    fat: 4.5,
    carbs: 28,
    protein: 3.2,
    sodium: 75,
    calcium: '10%',
    iron: '1%',
  },
  {
    id: 46,
    name: 'Sorbet',
    calories: 134,
    fat: 0.3,
    carbs: 34,
    protein: 0.9,
    sodium: 5,
    calcium: '1%',
    iron: '1%',
  },
  {
    id: 47,
    name: 'Profiteroles',
    calories: 334,
    fat: 22.1,
    carbs: 29,
    protein: 7.8,
    sodium: 178,
    calcium: '6%',
    iron: '8%',
  },
  {
    id: 48,
    name: 'Cannoli',
    calories: 298,
    fat: 19.5,
    carbs: 27,
    protein: 6.0,
    sodium: 337,
    calcium: '9%',
    iron: '5%',
  },
  {
    id: 49,
    name: 'Baklava',
    calories: 334,
    fat: 23.3,
    carbs: 29,
    protein: 4.2,
    sodium: 242,
    calcium: '6%',
    iron: '7%',
  },
  {
    id: 50,
    name: 'Tres Leches Cake',
    calories: 348,
    fat: 11.8,
    carbs: 54,
    protein: 7.9,
    sodium: 223,
    calcium: '18%',
    iron: '4%',
  },
  {
    id: 51,
    name: 'Chocolate Truffle',
    calories: 59,
    fat: 4.2,
    carbs: 5,
    protein: 0.6,
    sodium: 8,
    calcium: '1%',
    iron: '2%',
  },
  {
    id: 52,
    name: 'Panna Cotta',
    calories: 156,
    fat: 11.8,
    carbs: 10,
    protein: 2.8,
    sodium: 40,
    calcium: '8%',
    iron: '1%',
  },
  {
    id: 53,
    name: 'Trifle',
    calories: 267,
    fat: 11.2,
    carbs: 39,
    protein: 4.5,
    sodium: 112,
    calcium: '7%',
    iron: '4%',
  },
  {
    id: 54,
    name: 'Pavlova',
    calories: 209,
    fat: 0.1,
    carbs: 52,
    protein: 3.0,
    sodium: 67,
    calcium: '1%',
    iron: '1%',
  },
  {
    id: 55,
    name: 'Sticky Toffee Pudding',
    calories: 468,
    fat: 15.2,
    carbs: 82,
    protein: 4.1,
    sodium: 467,
    calcium: '6%',
    iron: '9%',
  },
  {
    id: 56,
    name: 'Black Forest Cake',
    calories: 367,
    fat: 16.1,
    carbs: 55,
    protein: 4.9,
    sodium: 243,
    calcium: '5%',
    iron: '12%',
  },
  {
    id: 57,
    name: 'Millionaire Shortbread',
    calories: 512,
    fat: 28.4,
    carbs: 61,
    protein: 5.2,
    sodium: 234,
    calcium: '6%',
    iron: '7%',
  },
  {
    id: 58,
    name: 'Lemon Meringue Pie',
    calories: 303,
    fat: 10.7,
    carbs: 53,
    protein: 4.2,
    sodium: 165,
    calcium: '4%',
    iron: '5%',
  },
  {
    id: 59,
    name: 'Banana Split',
    calories: 894,
    fat: 31.0,
    carbs: 154,
    protein: 15.0,
    sodium: 177,
    calcium: '28%',
    iron: '8%',
  },
  {
    id: 60,
    name: 'Sundae',
    calories: 284,
    fat: 14.7,
    carbs: 37,
    protein: 4.1,
    sodium: 92,
    calcium: '12%',
    iron: '3%',
  },
  {
    id: 61,
    name: 'Fruit Salad',
    calories: 50,
    fat: 0.2,
    carbs: 13,
    protein: 0.9,
    sodium: 2,
    calcium: '2%',
    iron: '2%',
  },
  {
    id: 62,
    name: 'Chocolate Fondue',
    calories: 387,
    fat: 21.4,
    carbs: 49,
    protein: 4.8,
    sodium: 45,
    calcium: '8%',
    iron: '15%',
  },
  {
    id: 63,
    name: 'Strawberry Cheesecake',
    calories: 339,
    fat: 24.1,
    carbs: 27,
    protein: 5.8,
    sodium: 457,
    calcium: '10%',
    iron: '4%',
  },
  {
    id: 64,
    name: 'Chocolate Chip Muffin',
    calories: 426,
    fat: 16.4,
    carbs: 65,
    protein: 7.4,
    sodium: 386,
    calcium: '7%',
    iron: '12%',
  },
  {
    id: 65,
    name: 'Blueberry Pie',
    calories: 271,
    fat: 12.0,
    carbs: 41,
    protein: 2.8,
    sodium: 380,
    calcium: '2%',
    iron: '4%',
  },
  {
    id: 66,
    name: 'Peach Cobbler',
    calories: 354,
    fat: 10.8,
    carbs: 64,
    protein: 4.2,
    sodium: 428,
    calcium: '5%',
    iron: '6%',
  },
  {
    id: 67,
    name: 'Chocolate Soufflé',
    calories: 235,
    fat: 14.2,
    carbs: 24,
    protein: 6.8,
    sodium: 178,
    calcium: '7%',
    iron: '9%',
  },
  {
    id: 68,
    name: 'Crème Caramel',
    calories: 213,
    fat: 5.8,
    carbs: 36,
    protein: 6.1,
    sodium: 89,
    calcium: '15%',
    iron: '2%',
  },
  {
    id: 69,
    name: 'Opera Cake',
    calories: 445,
    fat: 24.7,
    carbs: 52,
    protein: 6.3,
    sodium: 167,
    calcium: '4%',
    iron: '13%',
  },
  {
    id: 70,
    name: 'Molten Lava Cake',
    calories: 578,
    fat: 34.2,
    carbs: 64,
    protein: 7.8,
    sodium: 245,
    calcium: '6%',
    iron: '19%',
  },
  {
    id: 71,
    name: 'Affogato',
    calories: 92,
    fat: 3.4,
    carbs: 12,
    protein: 2.1,
    sodium: 35,
    calcium: '6%',
    iron: '1%',
  },
  {
    id: 72,
    name: 'Beignets',
    calories: 318,
    fat: 17.5,
    carbs: 35,
    protein: 5.2,
    sodium: 267,
    calcium: '4%',
    iron: '9%',
  },
  {
    id: 73,
    name: 'Funnel Cake',
    calories: 760,
    fat: 44.0,
    carbs: 87,
    protein: 7.8,
    sodium: 734,
    calcium: '8%',
    iron: '15%',
  },
  {
    id: 74,
    name: 'Cotton Candy',
    calories: 220,
    fat: 0.0,
    carbs: 56,
    protein: 0.0,
    sodium: 0,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 75,
    name: 'Taffy',
    calories: 159,
    fat: 2.2,
    carbs: 37,
    protein: 0.0,
    sodium: 64,
    calcium: '1%',
    iron: '0%',
  },
  {
    id: 76,
    name: 'Fudge',
    calories: 469,
    fat: 17.8,
    carbs: 81,
    protein: 2.2,
    sodium: 54,
    calcium: '4%',
    iron: '4%',
  },
  {
    id: 77,
    name: 'Pralines',
    calories: 569,
    fat: 24.0,
    carbs: 92,
    protein: 4.8,
    sodium: 178,
    calcium: '7%',
    iron: '5%',
  },
  {
    id: 78,
    name: 'Marshmallows',
    calories: 318,
    fat: 0.2,
    carbs: 81,
    protein: 1.8,
    sodium: 80,
    calcium: '0%',
    iron: '1%',
  },
  {
    id: 79,
    name: 'Caramel Apple',
    calories: 287,
    fat: 2.8,
    carbs: 71,
    protein: 0.8,
    sodium: 147,
    calcium: '2%',
    iron: '3%',
  },
  {
    id: 80,
    name: 'Chocolate Bar',
    calories: 535,
    fat: 29.7,
    carbs: 59,
    protein: 7.6,
    sodium: 24,
    calcium: '19%',
    iron: '19%',
  },
  {
    id: 81,
    name: 'Gummy Bears',
    calories: 140,
    fat: 0.0,
    carbs: 32,
    protein: 2.0,
    sodium: 10,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 82,
    name: 'Chocolate Cookies',
    calories: 502,
    fat: 24.9,
    carbs: 67,
    protein: 5.9,
    sodium: 378,
    calcium: '4%',
    iron: '15%',
  },
  {
    id: 83,
    name: 'Oatmeal Cookies',
    calories: 467,
    fat: 19.3,
    carbs: 71,
    protein: 6.9,
    sodium: 356,
    calcium: '5%',
    iron: '12%',
  },
  {
    id: 84,
    name: 'Sugar Cookies',
    calories: 473,
    fat: 21.1,
    carbs: 68,
    protein: 4.9,
    sodium: 318,
    calcium: '3%',
    iron: '7%',
  },
  {
    id: 85,
    name: 'Snickerdoodles',
    calories: 457,
    fat: 19.8,
    carbs: 68,
    protein: 5.4,
    sodium: 267,
    calcium: '4%',
    iron: '8%',
  },
  {
    id: 86,
    name: 'Shortbread',
    calories: 502,
    fat: 23.4,
    carbs: 67,
    protein: 6.2,
    sodium: 312,
    calcium: '3%',
    iron: '9%',
  },
  {
    id: 87,
    name: 'Biscotti',
    calories: 421,
    fat: 14.6,
    carbs: 67,
    protein: 9.1,
    sodium: 289,
    calcium: '5%',
    iron: '11%',
  },
  {
    id: 88,
    name: 'Madeleines',
    calories: 443,
    fat: 17.8,
    carbs: 67,
    protein: 6.8,
    sodium: 234,
    calcium: '4%',
    iron: '10%',
  },
  {
    id: 89,
    name: 'Palmiers',
    calories: 134,
    fat: 8.7,
    carbs: 13,
    protein: 1.8,
    sodium: 87,
    calcium: '1%',
    iron: '3%',
  },
  {
    id: 90,
    name: 'Meringue',
    calories: 20,
    fat: 0.0,
    carbs: 5,
    protein: 0.4,
    sodium: 4,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 91,
    name: 'Nougat',
    calories: 431,
    fat: 12.8,
    carbs: 75,
    protein: 4.6,
    sodium: 45,
    calcium: '5%',
    iron: '3%',
  },
  {
    id: 92,
    name: 'Divinity Candy',
    calories: 105,
    fat: 0.0,
    carbs: 26,
    protein: 0.7,
    sodium: 12,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 93,
    name: 'Peanut Brittle',
    calories: 486,
    fat: 19.2,
    carbs: 75,
    protein: 7.8,
    sodium: 423,
    calcium: '4%',
    iron: '6%',
  },
  {
    id: 94,
    name: 'Toffee',
    calories: 549,
    fat: 32.1,
    carbs: 65,
    protein: 1.2,
    sodium: 224,
    calcium: '5%',
    iron: '2%',
  },
  {
    id: 95,
    name: 'Caramels',
    calories: 383,
    fat: 8.1,
    carbs: 76,
    protein: 4.6,
    sodium: 178,
    calcium: '12%',
    iron: '4%',
  },
  {
    id: 96,
    name: 'Rock Candy',
    calories: 394,
    fat: 0.0,
    carbs: 100,
    protein: 0.0,
    sodium: 0,
    calcium: '0%',
    iron: '0%',
  },
  {
    id: 97,
    name: 'Peppermint Bark',
    calories: 537,
    fat: 31.2,
    carbs: 62,
    protein: 6.8,
    sodium: 67,
    calcium: '15%',
    iron: '18%',
  },
  {
    id: 98,
    name: 'Chocolate Covered Strawberries',
    calories: 67,
    fat: 3.8,
    carbs: 8,
    protein: 0.8,
    sodium: 3,
    calcium: '2%',
    iron: '2%',
  },
  {
    id: 99,
    name: 'Fruit Leather',
    calories: 78,
    fat: 0.1,
    carbs: 20,
    protein: 0.4,
    sodium: 4,
    calcium: '1%',
    iron: '2%',
  },
  {
    id: 100,
    name: 'Dark Chocolate',
    calories: 598,
    fat: 42.6,
    carbs: 45,
    protein: 7.9,
    sodium: 12,
    calcium: '7%',
    iron: '67%',
  },
];
